version: "3"

services:
  php_env:
    build: .
    volumes:
      - ./website:/var/www/html
    ports:
      - 9000:80
      # - 7000:9000
      # command: php -S localhost:9000 -t public

  mysql_db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    # volumes: # - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 9001:80
    environment:
      - PMA_ARBITRARY=1
